name: SF2 workflow

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      release_id:
        required: true
        type: string
      release_url:
        required: true
        type: string
      audio_ext:
        default: flac
        required: false
        type: string
      image_ext:
        default: jpg
        required: false
        type: string
      file_name:
        default: ${{ github.event.repository.name }}
        required: false
        type: string

jobs:
  sfz:
    name: SF2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Upload metadata
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./plugins.json
          asset_name: plugins.json
          asset_content_type: application/json

      - name: Upload audio preview
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./${{ inputs.file_name }}.${{ inputs.audio_ext }}
          asset_name: ${{ inputs.file_name }}.${{ inputs.audio_ext }}
          asset_content_type: audio/${{ inputs.audio_ext }}

      - name: Upload image preview
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./${{ inputs.file_name }}.${{ inputs.image_ext }}
          asset_name: ${{ inputs.file_name }}.${{ inputs.image_ext }}
          asset_content_type: image/${{ inputs.image_ext }}

      - name: Compress lossless version
        run: 7z a ./${{ inputs.file_name }}.zip -r

      - name: Upload lossless version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./${{ inputs.file_name }}.zip
          asset_name: ${{ inputs.file_name }}.zip
          asset_content_type: application/zip

      - name: Install polyphone
        run: sudo apt-get update && sudo apt-get install polyphone

      - name: Create compact version
        run: |
          IFS=$'\n'
          for file in $(find . -type f -name '*.sf2'); do polyphone -2 -i "$file"; done
          find . -type f -name '*.sf2' -type f -delete

      - name: Compress compact version
        run: |
          rm ${{ inputs.file_name }}.zip
          7z a ./${{ inputs.file_name }}-compact.zip -r

      - name: Upload compact version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./${{ inputs.file_name }}-compact.zip
          asset_name: ${{ inputs.file_name }}-compact.zip
          asset_content_type: application/zip
